#数据源
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/huayumall_sms?useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
  #服务名称
  application:
    name: huayumall-coupon
#注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.12:8848
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/coupon/*.xml
  global-config:
    db-config:
      id-type: auto #全局主键直增
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#端口
server:
  port: 9900
ribbon:
  eager-load:
    enabled: true
    clients: distribution, material-product, outer-data
